// Builds the contracts with Foundry and exports what the apps need:
//   mobile/src/lib/contracts.ts   ABI + init bytecode, for deploying and calling from the phone
//   agent-mcp/abi.json            the KagiAccount ABI, for the agent server
// Constructor arguments are appended to the bytecode at deploy time.
// usage: node scripts/export.mjs   (from contracts/, with forge on PATH)
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const here = new URL('../', import.meta.url);
execFileSync('forge', ['build'], { cwd: here, stdio: 'inherit' });
const load = (name) => JSON.parse(readFileSync(new URL(`out/${name}.sol/${name}.json`, here), 'utf8'));

const out = [];
out.push('// Generated by contracts/scripts/export.mjs. Do not edit.');
for (const name of ['KagiAccount', 'RootTreasury']) {
  const a = load(name);
  out.push(`export const ${name}Abi = ${JSON.stringify(a.abi)} as const;`);
  out.push(`export const ${name}Bytecode = '${a.bytecode.object}' as const;`);
  console.log(name, 'init bytes', (a.bytecode.object.length - 2) / 2, 'runtime bytes', (a.deployedBytecode.object.length - 2) / 2);
}
writeFileSync(new URL('../mobile/src/lib/contracts.ts', here), `${out.join('\n')}\n`);
writeFileSync(new URL('../agent-mcp/abi.json', here), JSON.stringify(load('KagiAccount').abi));
